// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Vo
{

    public class Item
    {
        public string itemDefId;
        public int? count;
    }

    public class Progress
    {
        public List<Item> item;
    }

    public class RobotInfo
    {
        public int? userId;
        public int? moduleId;
        public int? moduleLv;
        public Progress progress;
        public int? isUnlock;
        public int? proficiency;
        public List<int> unlockSkill;
    }

}
