// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Vo
{

    public class WorktableStatus
    {
        public int? userId;
        public int? typeId;
        public int? status;
        public string itemRtime;
    }

}
