//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19462
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;



public class ItemMakeCDInfo
{
    public int type = 4;
    public int itemDefId;
    public long completeTime;
    public int cd;
    public List<Dictionary<int, int>> material;

    public bool isComplete
    {
        get
        {
            return this.completeTime<0;
        }
    }
}


public class FinalGetItemVo
{
    public int itemDefId;
    public int count;
    public int type;
}

public class ItemMakeCDInfoQueue
{
    public int type;
    public List<ItemMakeCDInfo> listInfo{get;private set;}
}
